"""
chat_api.py — Website Chat API (FastAPI)
=========================================
Endpoints:
  POST /chat/message      — Send a message, get a reply (JSON, non-streaming)
  GET  /chat/history      — Get session chat history
  POST /chat/reset        — Clear session
  GET  /chat/ticket/{ref} — Get ticket status

Auth:
  - Reads the same JWT that ps5 backend issues (shared JWT_SECRET)
  - If valid JWT: user_id, name, email auto-filled
  - If no JWT: anonymous session using session_id from header/cookie

Session IDs:
  - website uses X-Session-ID header (UUID generated by frontend on first load)
  - Prefixed "web:" to keep separate from WhatsApp sessions in Redis
"""

import json
from typing import Optional

import jwt
from fastapi import APIRouter, Depends, Header, HTTPException, Request
from pydantic import BaseModel

from agent.runner import run_agent
from core.config import settings
from core.logger import logger
from tickets.tickets import get_ticket, list_tickets
from whatsapp.session import clear_session, get_session_messages, _get_redis, _session_key

router = APIRouter(prefix="/chat", tags=["chat"])

TICKET_STATE_TTL = 3600


# ── Models ────────────────────────────────────────────────────────────────────

class ChatMessage(BaseModel):
    message: str
    session_id: str   # UUID from frontend localStorage


class ChatResponse(BaseModel):
    response: str
    intent: str
    confidence: str
    ticket_ref: Optional[str] = None
    session_id: str


# ── Auth helpers ──────────────────────────────────────────────────────────────

def _decode_jwt(token: str) -> Optional[dict]:
    """
    Decode the ps5 JWT token to get user info.
    Same secret + algorithm as ps5 backend.
    Returns None if invalid/expired.
    """
    try:
        payload = jwt.decode(
            token,
            settings.JWT_SECRET,
            algorithms=[settings.JWT_ALGORITHM],
        )
        return payload
    except Exception:
        return None


def _get_user_from_request(
    authorization: Optional[str] = Header(None),
) -> dict:
    """Extract user info from JWT Authorization header (Bearer token)."""
    user = {"user_id": None, "name": None, "email": None}

    if not authorization or not authorization.startswith("Bearer "):
        return user

    token = authorization.removeprefix("Bearer ").strip()
    payload = _decode_jwt(token)

    if payload:
        user["user_id"] = payload.get("userId") or payload.get("id")
        user["name"]    = payload.get("name") or payload.get("username")
        user["email"]   = payload.get("email")

    return user


def _web_session_key(session_id: str) -> str:
    return f"web:{session_id}"


# ── Ticket state helpers (same pattern as WhatsApp webhook) ───────────────────

async def _get_ticket_state(session_id: str) -> dict:
    try:
        redis = _get_redis()
        key = f"zupwell:web_ticket_state:{session_id}"
        raw = await redis.get(key)
        return json.loads(raw) if raw else {"stage": "idle", "draft": {}}
    except Exception:
        return {"stage": "idle", "draft": {}}


async def _save_ticket_state(session_id: str, stage: str, draft: dict) -> None:
    try:
        redis = _get_redis()
        key = f"zupwell:web_ticket_state:{session_id}"
        await redis.set(key, json.dumps({"stage": stage, "draft": draft}), ex=TICKET_STATE_TTL)
    except Exception as e:
        logger.warning("Failed to save web ticket state: %s", e)


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.post("/message", response_model=ChatResponse)
async def chat_message(
    body: ChatMessage,
    user: dict = Depends(_get_user_from_request),
):
    """
    Process a chat message and return the bot's response.

    Flow:
      1. Read JWT → get user_id, name, email (or anonymous)
      2. Load ticket state from Redis
      3. Run LangGraph agent
      4. Save updated ticket state
      5. Return response JSON
    """
    session_id = _web_session_key(body.session_id)

    # Load ticket state
    ticket_state = await _get_ticket_state(body.session_id)

    # Run agent
    result = await run_agent(
        user_input=body.message,
        session_id=session_id,
        source="website",
        user_id=user.get("user_id"),
        user_name=user.get("name"),
        user_email=user.get("email"),
        ticket_stage=ticket_state.get("stage", "idle"),
        ticket_draft=ticket_state.get("draft", {}),
    )

    # Save updated ticket state
    await _save_ticket_state(
        body.session_id,
        result.get("ticket_stage", "idle"),
        result.get("ticket_draft", {}),
    )

    ticket_ref = None
    if result.get("ticket_created"):
        ticket_ref = result["ticket_created"].get("ticket_ref")

    return ChatResponse(
        response=result["response"],
        intent=result["intent"],
        confidence=result["confidence"],
        ticket_ref=ticket_ref,
        session_id=body.session_id,
    )


@router.get("/history")
async def chat_history(session_id: str):
    """Return the conversation history for a session."""
    messages = await get_session_messages(_web_session_key(session_id))
    return {"session_id": session_id, "messages": messages}


@router.post("/reset")
async def chat_reset(session_id: str):
    """Clear conversation history and ticket state."""
    await clear_session(_web_session_key(session_id))
    try:
        redis = _get_redis()
        await redis.delete(f"zupwell:web_ticket_state:{session_id}")
    except Exception:
        pass
    return {"status": "reset", "session_id": session_id}


@router.get("/ticket/{ticket_ref}")
async def ticket_status(ticket_ref: str):
    """Public endpoint to check ticket status by reference number."""
    ticket = await get_ticket(ticket_ref)
    if not ticket:
        raise HTTPException(status_code=404, detail="Ticket not found")
    # Return only public-safe fields
    return {
        "ticket_ref": ticket["ticket_ref"],
        "subject":    ticket["subject"],
        "status":     ticket["status"],
        "category":   ticket["category"],
        "created_at": ticket["created_at"],
    }


# ── Admin endpoints ───────────────────────────────────────────────────────────

@router.get("/admin/tickets")
async def admin_tickets(
    status: Optional[str] = None,
    source: Optional[str] = None,
    limit: int = 50,
    x_admin_key: Optional[str] = Header(None),
):
    """List all support tickets — admin only."""
    if x_admin_key != settings.ADMIN_KEY:
        raise HTTPException(status_code=403, detail="Invalid admin key")
    tickets = await list_tickets(status=status, source=source, limit=limit)
    return {"tickets": tickets, "count": len(tickets)}
